### ISSUE TITLE
update for wagtail 2.0 Django >=1.11

### ISSUE THREAD

**Issue by timcknowles** [texperience/wagtail-pythonanywhere-quickstart#1]
Hi Timo, 

This is great and looks like it would solve my deployment problems (I'm trying to deploy my wagatail 2.0 site to pythonanywhere.

I was wondering what I would need to do to make this work for 2.0?

BW

Tim

**Comment by ScarletMcLearn** [comment]
same here.

how can i make it work with django 2 and wagtail 2?

**Comment by timorieber** [comment]
Thanks for raising this and sorry for the long delay!

Simply change the dependencies in `setup.py` to fit your needs and create the virtual environment with the python version of your choice. For all supported combinations of Wagtail, Django and Python please read the [Wagtail documentation](https://docs.wagtail.io/en/stable/releases/upgrading.html).

I've updated the readme file accordingly. Additionally I upgraded this quickstart to Wagtail 2.3 LTS, but left Django at 1.11 LTS and Python 3.6, as these are the latest supported LTS versions.
