### ISSUE TITLE
How to use it to deploy Django 2, Wagtail 2 sites?

### ISSUE THREAD

**Issue by ScarletMcLearn** [texperience/wagtail-pythonanywhere-quickstart#2]
How to use it to deploy Django 2, Wagtail 2 sites?

Any updates?

Does this still work?

**Comment by timorieber** [comment]
Closed as duplicate of #1. Please read https://github.com/texperience/wagtail-pythonanywhere-quickstart/issues/1#issuecomment-433607597 for more details.
